### ISSUE TITLE
It doesn't work in IE11 on windows 7 in combination with babel-polyfill

### ISSUE THREAD

**Issue by kasperpeulen** [WebReflection/babel-plugin-transform-builtin-classes#12] opened 2018-03-05 16:03 UTC
We use this plugin in production at our company.
But there seems to be a problem. 
In Internet explorer, I can not get this to work.
If I do this:

```javascript
    class List extends Array {}
    console.log(new List());
    console.log(new List(1));
    console.log(new List(1) instanceof List);
    console.log(new List(1) instanceof Array);
```

I get the following:

![image](https://user-images.githubusercontent.com/1035299/36985141-c42653f8-2096-11e8-8ee6-27dff31d1e9b.png)

To reproduce, I installed this virtual box on https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/:

![image](https://user-images.githubusercontent.com/1035299/36985188-e1f6af0e-2096-11e8-8723-e7087c5b0911.png)

**Comment by WebReflection** [comment] 2018-03-05 16:08
can I see your configuration file? as it is, this bug looks like you're not transpiling anything at all.

**Comment by kasperpeulen** [comment] 2018-03-05 16:41
Could it be that there is a conflict with babel polyfill?
It seems to work if I don't run babel polyfill.
I use version ^6.26.0

**Comment by WebReflection** [comment] 2018-03-05 16:45
You have two options:
  * be sure you are following [the instructions](https://github.com/WebReflection/babel-plugin-transform-builtin-classes#usage)
  * drop this and use Babel 7 which AFAIK shipped with this change in core

Closing for now seems it looks like not a bug of this project.

**Closed as completed by WebReflection** 2018-03-05 16:45 UTC
Labels: invalid

**Comment by kasperpeulen** [comment] 2018-03-06 10:12
Hi @WebReflection,

I'm following the instructions. 
I think I understand the issue now.

If I don't include babel polyfill everything works fine on IE11.

But try just a html page with the following scripts:
```html
<script src="/node_modules/babel-polyfill/dist/polyfill.js"></script>
<script src="/main.min.js"></script>
```

Where main is the babelified version of:

```javascript
class List extends Array {}
console.log(new List(1) instanceof List);
```

It will log false in IE11. But if I remove the babel-polyfill it works.
I think this may be because the babel polyfill makes IE11 "look" like a more modern version.
And therefore this babel plugin won't patch the class for IE11?
I actually have the same issue in and old firefox version I tested (Firefox 42).

This is the babel output of the  main.min.js file that I have:

```javascript
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var _fixBabelExtend = function (O) {
  var gPO = O.getPrototypeOf || function (o) {
    return o.__proto__;
  },
      sPO = O.setPrototypeOf || function (o, p) {
    o.__proto__ = p;
    return o;
  },
      construct = (typeof Reflect === "undefined" ? "undefined" : _typeof(Reflect)) === 'object' ? Reflect.construct : function (Parent, args, Class) {
    var Constructor,
        a = [null];
    a.push.apply(a, args);
    Constructor = Parent.bind.apply(Parent, a);
    return sPO(new Constructor(), Class.prototype);
  };

  return function fixBabelExtend(Class) {
    var Parent = gPO(Class);
    return sPO(Class, sPO(function Super() {
      return construct(Parent, arguments, gPO(this).constructor);
    }, Parent));
  };
}(Object);

var List = _fixBabelExtend(function (_Array) {
  _inherits(List, _Array);

  function List() {
    _classCallCheck(this, List);

    return _possibleConstructorReturn(this, (List.__proto__ || Object.getPrototypeOf(List)).apply(this, arguments));
  }

  return List;
}(Array));

console.log(new List(1) instanceof List);
```

We don't want to use babel 7 until it is officially released.

**Comment by WebReflection** [comment] 2018-03-06 10:37
Hi @kasperpeulen, it's good you found the issue, but it's not in this part of your stack, it's in the polyfill that breaks your browser instead of fixing only what's fixable.

Polyfills are a difficult matter, here you have a transformer that has been adopted by Babel 7 so ... nothing here will change ... like ... ever, unless it's a bug of **this** file.

3rd parts introduced issues are nothing I have honestly time to deal with. Please talk to the polyfill authors and see what they can do, thanks.

**Comment by kasperpeulen** [comment] 2018-03-06 11:29
Okay, I think the issue is that Reflect.construct is not polyfilled correctly.

I have found the following "hacky" solution, that we can use until babel 7 is released:

```javascript
class __TestArrayExtends extends Array{};
if (!(new __TestArrayExtends() instanceof __TestArrayExtends)) {
    Reflect = undefined;
}
```

So basically I unset Reflect, when we find out that Array is not extended properly. This fixes the problem.

**Comment by WebReflection** [comment] 2018-03-06 12:55
@kasperpeulen thanks for sharing.

As a long-time polyfills author, I myself prefer no polyfills when using these break code instead of improving it.

I think `Reflect` is one of those namespaces nobody should polyfill unless it really works as expected, which is AFAIK never the case.
